#1. What are the names of all the countries in the country table?

Select
country_name as Name_of_Countries
from customer_insights.country;

#2. What is the total number of customers in the customers table?

 Select
count(*) as Number_of_Customers
from Customer_insights.customers;

#3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?

Select * from customer_insights.customers;

Select
avg(age) as Avg_age
,can_email 
from customer_insights.customers
where can_email = 'Yes';

#4. How many orders were made by customers aged 30 or older?

select
count(*) as Order_Count
from customer_insights.orders o
inner join customer_insights.customers c on c.customer_id = o.customer_id
where c.age >= 30;

#5. What is the total revenue generated by each product category?

select
Category
,sum(price) as Total_Price
from customer_insights.products
group by category;

#6. What is the average price of products in the 'food' category?

select
Category
,avg(price) as Average_Price
from customer_insights.products
where category = 'Food'
group by category;

#7. How many orders were made in each sales channel (sales_channel column) in the orders table?

SELECT 
sales_channel
,count(*) as No_Of_Orders
from customer_insights.orders
group by sales_channel;

#8.What is the date of the latest order made by a customer who can receive marketing emails

Select * from customer_insights.customers;

select
max(date_shop)
from customer_insights.orders c join customer_insights.customers o on c.customer_id = o.customer_id
where can_email = 'Yes'
order by can_email;

#9. What is the name of the country with the highest number of orders?

Select
Country_name
,count(order_id) as No_of_Orders
from customer_insights.country c
 inner join customer_insights.orders o on c.country_id = o.country_id
 group by country_name
 order by count(order_id) desc
 limit 1;

#10. What is the average age of customers who made orders in the 'vitamins' product category?

select 
avg(c.age) as Average_age
,Category
from customer_insights.Products p
  inner join customer_insights.baskets b on p.product_id = b.product_id
  inner join customer_insights.orders o on b.order_id = o.order_id
  inner join customer_insights.customers c on o.customer_id = c.customer_id
  where P.category = 'Vitamins';
  
